# Generated by Django 4.1.4 on 2023-01-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='type',
        ),
        migrations.AddField(
            model_name='details',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='college',
            field=models.CharField(default='', max_length=50),
        ),
    ]
