# Generated by Django 4.1.4 on 2023-01-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_details_type_details_branch_details_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='branch',
            new_name='type',
        ),
    ]
