# Generated by Django 4.1.4 on 2023-01-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_branch_details_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
