# Generated by Django 4.1.4 on 2023-01-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_details_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='year',
            field=models.CharField(default='', max_length=50),
        ),
    ]
